language: python

python:
  - "3.7.4"

env:
  - DJANGO_VERSION=2.2.8

install:
  - pip install -r requirements.txt

script:
  - coverage run --source='.' manage.py test

services:
  - rabbitmq

addons:
  apt:
    packages:
      - rabbitmq-server

after-success:
  - codecov